### ISSUE TITLE
نیم فاصله و ه حمزه

### ISSUE THREAD

**Issue by amirmalekicom** [sinadarvi/windows-persian-keyboard-for-ubuntu#1]
سلام
همه چی (از جمله پ و بقیه چیزها) خیلی خوبه، ممنون.
ولی جای ه حمزه ة گذاشته شده و نیم فاصله هم موجود نیست...
راهی برای اصلاح وجود داره؟

**Comment by sinadarvi** [comment]
hi, yes, I didn't find ۀ in ubuntu anywhere, even in the standard keyboard! if you find it or find a solution for this notify me.
you can use `shift + space` for half-space.
anyhow if you want to contribute you can make a pull request and I will check it.

**Comment by sinadarvi** [comment]
closing this issue due to no further investigation.
