### ISSUE TITLE
problem in ubuntu  20

### ISSUE THREAD

**Issue by karimi12** [sinadarvi/windows-persian-keyboard-for-ubuntu#4]
hi 
i can`t use your layout on ubuntu 20.
1. in use automatic method.
2. choice ```Persian (Windows layout)```
after this works i cant choice Persian keyboard by ```Super+Space``` buttons

**Comment by karimi12** [comment]
solve it! 
need a reboot!

**Comment by sinadarvi** [comment]
I just want to mention that. closing this issue.
