### ISSUE TITLE
No Half-Space key 

### ISSUE THREAD

**Issue by rezarjz** [sinadarvi/windows-persian-keyboard-for-ubuntu#5]
Thank you for your effort.
My original reason to switch to your keyboard was that there was no hashtag key for linux persian keybaord.
however, now there is no half-sapce button (virtual space as in می رود)
could you address this problem?

**Comment by sinadarvi** [comment]
@rezarjz, as far as I could remember I did provide half-space in the keyboard, but unfortunately, I don't have any active Linux OS to test it, so there is no help that I could provide. but @ghhabib2 did a major modification on the code, so maybe he could help.

**Comment by ghhabib2** [comment]
Thank you, @rezarjz, for addressing the problem. I believe I already added it to the keyboard. But I should double-check it.
I have an active Linux but unfortunately allowed to use it in multi-language mode. But I'll try to install one on my PC and try to solve this problem.

**Comment by sinadarvi** [comment]
I remembered [this issue](https://github.com/sinadarvi/windows-persian-keyboard-for-ubuntu/issues/1#issuecomment-435350731). In the previous version, we did have half-space as `shift+space`. I think this will do the same in the current version. @rezarjz would you please check it?

**Comment by rezarjz** [comment]
Thank you guys, I'll check it out
