### ISSUE TITLE
Rename this project to  windows-persian-keyboard-for-linux

### ISSUE THREAD

**Issue by MasterKia** [sinadarvi/windows-persian-keyboard-for-ubuntu#6]
As this script worked on my Manjaro installation so it does work on Arch based distros as well as Debian based distros (like Ubuntu).

So it's safe to assume that it would work on any Linux distribution therefore the project no longer needs to be named "
windows-persian-keyboard-for-ubuntu" and you could rename it to "windows-persian-keyboard-for-**linux**".

**Comment by sinadarvi** [comment]
Dear @MasterKia,
I assume it would work on other distros but for making sure I have to check this myself.
Currently, I do not own any Linux-based system to test it. but I can ask my friends and colleagues to test it for me.
further updates will be available here.
Thanks for letting me know that.

**Comment by MasterKia** [comment]
Came to say that it does work on Fedora 35 (with wayland).

**Comment by MasterKia** [comment]
Came to say that it does work on Fedora 35 (GNOME + Wayland).

**Comment by sinadarvi** [comment]
thank you for investigating that. I will make a proper change later.
